version: "3.8"

services:
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    
    volumes:
      - mongo_data:/data/db
    networks:
      - mynett
    

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "4000:4000"
    environment:
      MONGO_URL: "mongodb://mongo:27017/todo"
    
    depends_on:
      - mongo
    
    networks:
      - mynett

volumes:
  mongo_data:

networks:
  mynett: